### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by polarker**
I moved `Overview` and `FAQ` to the top layer to make them more accessible.

Screenshot 2022-10-03 at 09 57 04

### CODE REVIEW

**Comment by Sakrecoer** [comment]
This is great! We'd just need to reflect the changes in the french translation before we push it to production. I can take care of that tomorrow :)

**Comment by polarker** [comment]
> We'd just need to reflect the changes in the french translation

Thanks for the reminder !

**Comment by polarker** [comment]
@Sakrecoer I will introduce many more changes to the structure, let's fix the french translation afterwards.

**Comment by Sakrecoer** [comment]
@polarker Ok! :) Thanks for the heads-up!

**Pull request merged**
