### PR TITLE
Wiki fixes ilias

### PR DESCRIPTION
**Pull request by nop33**
@LeeAlephium I removed the note placeholder for the video in the _"A primer with the desktop wallet"_ because linking to this "unfinished" page from our website looks unprofessional (I reported it here in my [review](https://github.com/alephium/www/pull/83#pullrequestreview-1019983919)).

I also applied formatting to all files.

### CODE REVIEW

**Comment by LeeAlephium** [comment]
All good, but for what it's worth, nothing on that page can even be completed... Should we remove it entirely?

**Comment by nop33** [comment]
Sure, let's remove it. Will you take care of it? (remove translation file as well)

**Review by Sakrecoer — APPROVED** [review]
This is some serious attention to details, thank you @nop33! Looking good to me!

**Comment by Sakrecoer** [comment]
> Will you take care of it?

I am assuming "you" is @LeeAlephium in this context...? :sweat_smile: If Lee's busy as hell, don't hesitate to pass it on to me. I will need to do edits this week anyways.

**Comment by nop33** [comment]
I removed it :)

**Comment by Sakrecoer** [comment]
Looking good to me! Thank you @nop33 <3

**Pull request merged**
