### PR TITLE
Update dApps section pages

### PR DESCRIPTION
**Pull request by nop33**
Related to #50

@polarker, what do you think of the overview page content that I created (you can leave comments on the diff)? I could link the website to that page, as proposed on Slack:

image

@Sakrecoer @VDAODAO what do you think about the changes in general?

@Sakrecoer how do we deal with updating the French part?

### CODE REVIEW

**Comment by LeeAlephium** [comment]
I'd change the Note into Warning

**Comment by polarker** [comment]
The overview part LGTM, thanks ❤️

**Comment by Sakrecoer** [comment]
Awesome @nop33 
 I can translate this to french and add it to the branch if that's cool with you

**Comment by Sakrecoer** [comment]
I agree with @LeeAlephium regarding the usage of `:::warning` instead of `:::info` for this particular message.

**Comment by nop33** [comment]
@LeeAlephium @Sakrecoer how about :::caution?

image

**Comment by Sakrecoer** [comment]
I came back to propose `:::caution` as well :D

**Comment by Sakrecoer** [comment]
Translation and synch done! For me this is ready for merge! :tada:

**Review by Sakrecoer — APPROVED** [review]

**Pull request merged**
