### PR TITLE
Migrating missing content and changing pages order

### PR DESCRIPTION
**Pull request by nop33**
Related to #12

### CODE REVIEW

**Review by Sakrecoer — APPROVED** [review]
LGTM! :raised_hands: Thank you!

**Comment by Sakrecoer** [comment]
I'll let you do it, but for reference: which is the preferred way to merge here?

**Comment by nop33** [comment]
1 person gives their approval and the creator of the PR can then merge.

**Comment by Sakrecoer** [comment]
Cheers @nop33 what i wonder is which strategy? `create merge commit`, `squash and merge` or `Rebase and merge`?

**Comment by nop33** [comment]
Create merge commit

**Pull request merged**
