### PR TITLE
Adding ALPH-pool to the pool-list

### PR DESCRIPTION
**Pull request by Sakrecoer**
Adaptation of https://github.com/alephium/wiki/pull/60 by @alex-oleshkevich 
(Original PR proposed the addition in chronological order where we use Alphabetic order.)

### CODE REVIEW

**Review by LeeAlephium — APPROVED** [review]
Looks good to me but I'd get @MaudSimon to look over this too since there's a legal excerpt in here

**Comment by Sakrecoer** [comment]
So far we've added pools indiscriminately since we have a disclaimer for the purpose. We however remove inactive ones and keep an eye on the color of the hats :sweat_smile: So i will go ahead and merge it! Just needed that review to stay within the rules we agreed uppon. Many thanks @LeeAlephium :purple_heart:

**Comment by Sakrecoer** [comment]
@LeeAlephium oh wait, i see what you mean. The legal excerpt has been in production for a long time. It wasn't updated in the french version (which we need to keep in synch because we can't use the fall back English due to the message inserted to invite for translation) Probably should have done that separately. Will remember for future cases.

**Comment by MaudSimon** [comment]
@Sakrecoer Is there anything you need me to do here ?

**Comment by Sakrecoer** [comment]
@MaudSimon Thank you, it's all good and closed :)

**Pull request merged**
