### PR TITLE
Add Pruning Instruction using Docker

### PR DESCRIPTION
**Pull request by h0ngcha0**

### CODE REVIEW

**Comment by MaudSimon** [comment]
@h0ngcha0 any reason why you haven't merged the PR ?

**Review by Lbqds — APPROVED** [review]
LGTM 👍

**Comment by MaudSimon** [comment]
@h0ngcha0 will merge the PR once the docket pruning PR on full node is merged. @h0ngcha0 maybe you could link it in a comment ?

**Comment by h0ngcha0** [comment]
> @h0ngcha0 will merge the PR once the docket pruning PR on full node is merged. @h0ngcha0 maybe you could link it in a comment ?

Yes, thanks for pushing for this :100: 

This PR will be merged after this [PR](https://github.com/alephium/alephium/pull/1017) on full node.

**Comment by killerwhile** [comment]
the version in the doc could be bump'ed to v2.8.0

**Pull request merged**
