### PR TITLE
fix: typo with markdown url

### PR DESCRIPTION
**Pull request by sven-hash**

### CODE REVIEW

**Comment by Sakrecoer** [comment]
Thank you @sven-hash, but what's wrong with having a period at the end of a sentence?

**Comment by Sakrecoer** [comment]
Oh, i see! :) 

Need to add it back after the markdown link though

**Review by Sakrecoer — CHANGES_REQUESTED** [review]
Thanks! Please add the period after the the markdown link and i will merge the fix :) :purple_heart:

**Comment by sven-hash** [comment]
@Sakrecoer done! Normally you have the right to edit the file if you're going under "Files changed" -> the 3 dots on the right and then "edit file"

**Comment by Sakrecoer** [comment]
@sven-hash i don't think i can edit your fork, i don't see those 3 dots. So i would have to merge your changes to a branch, edit it, close your PR, open a new PR and merge.

Either way thanks!

**Review by Sakrecoer — APPROVED** [review]

**Pull request merged**
