### PR TITLE
Update Desktop Wallet Section

### PR DESCRIPTION
**Pull request by MaudSimon**

### CODE REVIEW

**Comment by Sakrecoer** [comment]
For some reason, when using MDX compliant image tag (necessary to avoid build fail), the `height` attribute has no effect. It would look nice if it was used in some parts of the "getting started" guide for the desktop wallet. If you know how to get the height attributes to work in this context, @nop33 or @mvaivre, please advise :purple_heart: Otherwise i will find a way to crop the images manually.

**Comment by nop33** [comment]
> For some reason, when using MDX compliant image tag (necessary to avoid build fail), the height attribute has no effect. 

The reason is that the `height` attribute of the `img` tag that you are specifying is getting overridden by our theme:

```
.img_node_modules-\@docusaurus-theme-classic-lib-next-theme-MDXComponents-Img-module {
    height: auto;
}
```

I tried overriding the theme, but I didn't succeed because whatever I add in the custom CSS file also gets overridden (oh, the irony). https://docusaurus.io/docs/api/themes/@docusaurus/theme-classic#ex-config

What you can do, however, is to use the `style` HTML attribute, like so:

```
<img src={require("./media/gs1.png").default} alt="Landing page" style={{ height: '100px' }}/>
```

---

I found it a bit annoying that I cannot click on the image to zoom in. So, I added a commit to add this plugin: https://github.com/gabrielcsapo/docusaurus-plugin-image-zoom. Now, when you clean on an image, no matter how you styled it with `width` and `height`, it will zoom it to fit the screen.

**Comment by nop33** [comment]
I would also recommend the following:
1. When writing a numbered list as a guide, the images should (imo) appear **after** the text. I think it's better when the reader first reads the text and then sees the image for context instead of the other way around.
2. When adding images inside a numbered list, there should be enough whitespace before the image as there is for the numbered list text. Example (see how the word "Click" and "image
   It also adds this nice shadow that I really love, which allows us to remove these ugly `&nbsp;&nbsp;&nbsp;&nbsp;` from the markdown file.

**Comment by MaudSimon** [comment]
Thx Ilias, for 1. I was following what Hongchao did in the extension section. I'll work with Set on replacing the screenshots.

**Comment by Sakrecoer** [comment]
Thanks a million @nop33! This is amazing and far better than the expectations.
I have changed the order of images, added alt description to each one of them and corrected the formatting issues. While i have consolidated the height of the images, i think its worth using macs nifty screenshot as they are quite beautiful. Perhaps @MaudSimon can do the new images and we'll look at incoporating them together later today.

**Pull request merged**
