### PR TITLE
Running dockerized full node from a VPS / dedicated server (running ubuntu)

### PR DESCRIPTION
**Pull request by sacredland**
Based on [the official Alephium procedure](https://github.com/alephium/alephium/tree/master/docker)

1) Make an user from where you will run the node, i.e. alephium, with admin right
**sudo adduser alephium**
**sudo adduser alephium sudo**

2) Install depedencies
**sudo apt install default-jdk**
**sudo apt install docker docker-compose**

2) Get the docker rep from Github
**git clone https://github.com/alephium/alephium.git**

3) Go inside /home/_USER_/alephium/docker dir and copy (or move) the files to your /home/
copy: **cp docker-compose.explorer.yml  docker-compose.gpu-miner.yml  docker-compose.yml  grafana  prometheus  README.md  release  user.conf ~/**
move: **mv docker-compose.explorer.yml  docker-compose.gpu-miner.yml  docker-compose.yml  grafana  prometheus  README.md  release  user.conf ~/**

4) Get back to your /home/ 

5) Edit user.conf (API section)

6) If you don't want to use sudo each time, type **sudo usermod -aG docker $USER** and reconnect to the machine after

7) Lunch your container 
**docker-compose stop && docker-compose rm -f alephium && docker-compose pull && docker-compose up -d**

8) From that terminal, on your actual PC type:
**ssh -L 12973:localhost:12973 user@hostname/ip** 

9) Then, open a navigator from your actual PC and go to [http://127.0.0.1:12973/docs](http://127.0.0.1:12973/docs) (the localhost of the remote machine) to create/edit your Swagger UI. 

Your node should be syncing and running.

Check stats
**http://REMOTE-IP:3000/d/ME6diT3Mk/jvm-overview?orgId=1&refresh=30s**

**http://REMOTE-IP:3000/d/S3eJTo3Mk/alephium-overview?orgId=1&refresh=30s**

### CODE REVIEW

**Comment by sacredland** [comment]
Missing the part 
mkdir ./alephium-data ./alephium-wallets && chown nobody ./alephium-data ./alephium-wallets

**Comment by Sakrecoer** [comment]
When i look at this PR it seems like it is to merge _from_ `master` into `update-technical-guide-fullnode` which seems a bit backwards?

@sacredland am i getting this right if i think that you would like the text you pasted in the issue to appear here: https://wiki.alephium.org/full-node/Docker-Guide ?

**Comment by Sakrecoer** [comment]
I will close the PR, but don't be discouraged @sacredland ! You can still clarify the intention here and as soon as we figure it out together, we'll find the adequate way to act :)

**Comment by sacredland** [comment]
Yes go for itEnvoyé de mon iPhoneLe 15 sept. 2022 à 08:51, Set Hallstrom ***@***.***> a écrit :﻿
When i look at this PR it looks like it is merging from master to update-technical-guide-fullnode which seems a bit backwards?
@sacredland am i getting this right if i think that you would like the text you pasted in the issue to appear here: https://wiki.alephium.org/full-node/Docker-Guide ?

**Pull request closed without merging**
