### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Comment by Sakrecoer** [comment]
Thank you very much @omahs. Despite the long response time, please rest assured your contribution is very appreciated! :)

**Review by Sakrecoer — APPROVED** [review]

**Review by Sakrecoer — APPROVED** [review]

**Comment by Sakrecoer** [comment]
Greetings @omahs!

I'm trying to contact you in order to reward you for this contribution. But i am unsure how to best proceed since GitHub has no private messages. Are you familiar with pgp/gpg? If you are you could perhaps provide your public key here and sign your email with it? Otherwise, feel free to send an email to community@alephium.org mentioning the URL of this issue, and i will reply to you with a string for you to paste in this issue in order to verify the email is really coming from you.

**Comment by omahs** [comment]
Hey @Sakrecoer nice thanks! I'll send an email :)

**Comment by omahs** [comment]
mXgPAwXYJ5ptYDO5ZtnT8w0kd

**Comment by Sakrecoer** [comment]
Awesome! Thank you very much for your prompt response and compliance! Sending you the info asap!

**Pull request merged**
